baseURL = "https://erikjohannes.no/"
languageCode = "en-us"
title = "Erik Johannes Husom"
sectionPagesMenu = "main"

[params]
  author = "Erik Johannes Husom"
  github = "https://github.com/ejhusom"
  mastodon = "https://mastodon.social/@erikjohannes"
  pixelfed = "https://pixelfed.social/erikjohannes"
  instagram = "https://instagram.com/erikjohannes"
  mainSections = ["posts", "notes", "science", "links"]


